import { DictationLesson } from "@/types/dictation";

export const mockDictationLesson: DictationLesson = {
  id: "dictation-001",
  title: "Basic Greetings",
  description: "Learn how to write basic Vietnamese greetings",
  totalQuestions: 5,
  currentQuestionIndex: 0,
  lives: 5,
  maxLives: 5,
  progress: 0,
  isCompleted: false,
  score: 0,
  questions: [
    {
      id: "q1",
      type: "new_word",
      instruction: "Write this in English",
      targetWord: "Chào!",
      targetLanguage: "vi",
      answerLanguage: "en",
      wordOptions: [
        { id: "w1", text: "passport", isCorrect: false },
        { id: "w2", text: "yes", isCorrect: false },
        { id: "w3", text: "Hi", isCorrect: true },
        { id: "w4", text: "Hello", isCorrect: true },
        { id: "w5", text: "I", isCorrect: false },
      ],
      correctAnswer: "Hi",
      explanation: "Chào! means 'Hi' or 'Hello' in Vietnamese",
      audioUrl: "/audio/chao.mp3",
    },
    {
      id: "q2",
      type: "new_word",
      instruction: "Write this in English",
      targetWord: "Tạm biệt",
      targetLanguage: "vi",
      answerLanguage: "en",
      wordOptions: [
        { id: "w6", text: "Goodbye", isCorrect: true },
        { id: "w7", text: "Thank you", isCorrect: false },
        { id: "w8", text: "Please", isCorrect: false },
        { id: "w9", text: "Sorry", isCorrect: false },
        { id: "w10", text: "Excuse me", isCorrect: false },
      ],
      correctAnswer: "Goodbye",
      explanation: "Tạm biệt means 'Goodbye' in Vietnamese",
      audioUrl: "/audio/tam-biet.mp3",
    },
    {
      id: "q3",
      type: "review_word",
      instruction: "Write this in Vietnamese",
      targetWord: "Thank you",
      targetLanguage: "en",
      answerLanguage: "vi",
      wordOptions: [
        { id: "w11", text: "Xin chào", isCorrect: false },
        { id: "w12", text: "Cảm ơn", isCorrect: true },
        { id: "w13", text: "Xin lỗi", isCorrect: false },
        { id: "w14", text: "Làm ơn", isCorrect: false },
        { id: "w15", text: "Tạm biệt", isCorrect: false },
      ],
      correctAnswer: "Cảm ơn",
      explanation: "Thank you is 'Cảm ơn' in Vietnamese",
      audioUrl: "/audio/cam-on.mp3",
    },
    {
      id: "q4",
      type: "new_word",
      instruction: "Write this in English",
      targetWord: "Xin lỗi",
      targetLanguage: "vi",
      answerLanguage: "en",
      wordOptions: [
        { id: "w16", text: "Sorry", isCorrect: true },
        { id: "w17", text: "Please", isCorrect: false },
        { id: "w18", text: "Thank you", isCorrect: false },
        { id: "w19", text: "Hello", isCorrect: false },
        { id: "w20", text: "Goodbye", isCorrect: false },
      ],
      correctAnswer: "Sorry",
      explanation: "Xin lỗi means 'Sorry' in Vietnamese",
      audioUrl: "/audio/xin-loi.mp3",
    },
    {
      id: "q5",
      type: "review_word",
      instruction: "Write this in Vietnamese",
      targetWord: "Please",
      targetLanguage: "en",
      answerLanguage: "vi",
      wordOptions: [
        { id: "w21", text: "Làm ơn", isCorrect: true },
        { id: "w22", text: "Xin lỗi", isCorrect: false },
        { id: "w23", text: "Cảm ơn", isCorrect: false },
        { id: "w24", text: "Xin chào", isCorrect: false },
        { id: "w25", text: "Tạm biệt", isCorrect: false },
      ],
      correctAnswer: "Làm ơn",
      explanation: "Please is 'Làm ơn' in Vietnamese",
      audioUrl: "/audio/lam-on.mp3",
    },
  ],
}; 