---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: puchi-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: puchi-prod
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    persistentvolumeclaims: "50"
    pods: "100"
    services: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: puchi-dev
spec:
  limits:
    - default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      type: Container
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: puchi-prod
spec:
  limits:
    - default:
        cpu: "4"
        memory: "8Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
      type: Container
