apiVersion: apps/v1
kind: Deployment
metadata:
  name: puchi-fe
  namespace: puchi
  labels:
    app: puchi-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puchi-fe
  template:
    metadata:
      labels:
        app: puchi-fe
    spec:
      containers:
        - name: puchi-fe
          image: hoanit/puchi-fe:dev
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: puchi-fe-config
            - secretRef:
                name: puchi-fe-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
