apiVersion: v1
kind: Service
metadata:
  name: { { include "go-service.fullname" . } }
  labels:
    app.kubernetes.io/name: { { include "go-service.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
spec:
  type: { { .Values.service.type } }
  selector:
    app.kubernetes.io/name: { { include "go-service.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
