apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: puchi-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "puchi_dev"
            - name: POSTGRES_USER
              value: "puchi"
            - name: POSTGRES_PASSWORD
              value: "puchi123"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - puchi
                - -d
                - puchi_dev
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - puchi
                - -d
                - puchi_dev
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: puchi-dev
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
