apiVersion: apps/v1
kind: Deployment
metadata:
  name: puchi-fe
  namespace: puchi-dev
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: puchi-fe
          image: ghcr.io/hoan02/puchi-app/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api-dev.puchi.io.vn"
            - name: NEXT_PUBLIC_APP_URL
              value: "https://dev.puchi.io.vn"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: puchi-fe
  namespace: puchi-dev
spec:
  selector:
    app: puchi-fe
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
