apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - frontend-patch.yaml
  - user-service-patch.yaml
  - database-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn
      - API_URL=https://api.puchi.io.vn

secretGenerator:
  - name: app-secrets
    literals:
      - DATABASE_URL=postgres://puchi:prod-secure-password@postgres:5432/puchi_prod
      - DATABASE_PASSWORD=prod-secure-password
      - JWT_SECRET=prod-jwt-secret-key
      - ENCRYPTION_KEY=prod-encryption-key

images:
  - name: ghcr.io/hoan02/puchi-app/frontend
    newTag: latest
  - name: ghcr.io/hoan02/puchi-app/user-service
    newTag: latest

namespace: puchi-prod

commonLabels:
  environment: production
  app.kubernetes.io/managed-by: kustomize
