apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: platform
type: Opaque
stringData:
  # Create token in Cloudflare dashboard: Zero Trust > Tunnels > Create Tunnel
  # Then set repository secret K8S_CLOUDFLARED_TUNNEL_TOKEN and apply via CI
  TUNNEL_TOKEN: "REPLACE_ME_WITH_TUNNEL_TOKEN"
