apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: platform
spec:
  selector:
    app.kubernetes.io/name: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
